### ISSUE TITLE
getting Exception "cannot create source from adapter" when running migration version

### ISSUE THREAD

**Issue by Zxurian** [vgarvardt/ZfSimpleMigrations#9]
```
[rgoodrow@ariel ~]$ dev.hub migration version
======================================================================
   The application has thrown an exception!
======================================================================
 Exception
 cannot create source from adapter
----------------------------------------------------------------------
/var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/Db/Metadata/Metadata.php:60
#0 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/Db/Metadata/Metadata.php(36): Zend\Db\Metadata\Metadata->createSourceFromAdapter(Object(Zend\Db\Adapter\Adapter))
#1 /var/www/dev.hub/vendor/vgarvardt/zf-simple-migrations/src/ZfSimpleMigrations/Library/Migration.php(48): Zend\Db\Metadata\Metadata->__construct(Object(Zend\Db\Adapter\Adapter))
#2 /var/www/dev.hub/vendor/vgarvardt/zf-simple-migrations/src/ZfSimpleMigrations/Controller/MigrateController.php(132): ZfSimpleMigrations\Library\Migration->__construct(Object(Zend\Db\Adapter\Adapter), Array, Object(ZfSimpleMigrations\Model\MigrationVersionTable), Object(ZfSimpleMigrations\Library\OutputWriter))
#3 /var/www/dev.hub/vendor/vgarvardt/zf-simple-migrations/src/ZfSimpleMigrations/Controller/MigrateController.php(48): ZfSimpleMigrations\Controller\MigrateController->getMigration()
#4 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(82): ZfSimpleMigrations\Controller\MigrateController->versionAction()
#5 /var/www/dev.hub/vendor/vgarvardt/zf-simple-migrations/src/ZfSimpleMigrations/Controller/MigrateController.php(28): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 [internal function]: ZfSimpleMigrations\Controller\MigrateController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/dev.hub/html/index.php(17): Zend\Mvc\Application->run()
#16 {main}
======================================================================
```

**Comment by Zxurian** [comment]
this is just after adding via composer, using cli to generate skeleton, and running list

**Comment by jeremygiberson** [comment]
Are you by chance using sqlite as your driver options?

**Comment by Zxurian** [comment]
nope, mysql.

**Comment by AlmasK** [comment]
I got followed errors: 
Zend\ServiceManager\Exception\ServiceNotCreatedException An exception was raised while creating "ZfSimpleMigrations\Controller\Migrate"; no instance returned

Previous Exception(s):
Zend\ServiceManager\Exception\ServiceNotCreatedException
 An abstract factory could not create an instance of migrations.migration.default(alias: migrations.migration.default).

Zend\ServiceManager\Exception\ServiceNotFoundException
 Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for Zend\Db\Adapter\Adapter

Reason "Zend\Db\Adapter\Adapter" not defined as service in migration module configuration.
Just add 
'service_manager' => [
        'factories' => [
            'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory'
        ]
    ] 
to module.config.php  and everything works!
